### ISSUE TITLE
Error 401: Unauthorized

### ISSUE THREAD

**Issue by McShuibhne** [n3mo/massmine#6]
Hi. I'd like to use Massmine for my doctoral thesis, but I'm getting this error when trying to run it:

![captura de pantalla 2015-05-24 a la s 11 38 04](https://cloud.githubusercontent.com/assets/12582750/7787383/6b0702c6-0209-11e5-9924-a88993d84a89.png)

**Comment by n3mo** [comment]
Thanks for your interest in MassMine. I've committed a patch to this problem. You should be able to get up an running in two steps:

(1) Update MassMine on your computer with the follow commands:
```sh
    cd ~/path/to/massmine/
    git pull
```
(2) You will need to add two lines to your configuration file---your Twitter "Access Token" and "Access Token Secret". Please see the updated file mmconfig in the "examples" folder of your massmine installation to see how to properly format these. These keys are available at [Twitter's Application Site](https://apps.twitter.com/)

Once you have complete these steps, you should be able to proceed with the installation and Twitter authentication steps described on [MassMine's Documentation](http://www.massmine.org/docs/index.html)

Cheers!
Nick

**Comment by McShuibhne** [comment]
Thank you so much!

**Comment by n3mo** [comment]
No problem! Let me know if you run into any further issues. Also, I'd love to hear how you're using MassMine in your research (if you're able to share).
