### ISSUE TITLE
OAuth incorrectly called

### ISSUE THREAD

**Issue by dcfaltesek** [n3mo/massmine#7]
I downloaded the zip and changed the mmconfig to include my information and when I return to run massmine I get:

[1] "Using direct authentication"
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'
Calls: loadModules ... mmAuth -> setup_twitter_oauth -> check_twitter_oauth
Execution halted
logout

Could this be an issue on my end?

**Comment by n3mo** [comment]
It seems that you are using an older, prototype version of massmine. Massmine is being completely rewritten (and improved) in anticipation of its "official" release. Fortunately, there is a working version just recently released for 64 bit Linux and a specially compiled version for University of Florida Research Computing users that renders your issue... well, a non-issue. Instructions for how to install and use the new massmine are available on the [MassMine website](http://www.massmine.org). There are now zero dependencies, installation is simple, and there are more features than ever.

The [official website](http://www.massmine.org) has enough instructions to get you going. I am working with others on developing many examples and full documentation, which you can expect to see online soon. In the meantime, you are welcome to contact me here with any questions. I would be happy to help get you going!

**Comment by dcfaltesek** [comment]
I look forward to it, in the meantime twitteR and paid services will cover
my needs. Keep up the good work.

Dan
